name: agenda_contatos
description: Agenda de Contatos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^2.2.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^8.1.0
  flutter_masked_text: ^0.8.0
  googleapis: ^3.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.7.5+3
  intl: ^0.17.0
  intl_phone_field: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  libphonenumber: ^2.0.0
  random_color: ^1.0.5
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.1+1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400


# flutter pub run flutter_launcher_icons:main && flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_192.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon_900.png
  fullscreen: true
